version: '3.3'

services:
  recommandation-service:
    container_name: recommandation-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8082:8082'
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://recommandation-database:5432/recommandationsdb
      SPRING_DATASOURCE_USERNAME: sonia
      SPRING_DATASOURCE_PASSWORD: caramelpsql2
    depends_on:
      - recommandation-database

  recommandation-database:
    container_name: recommandation-database
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_USER: sonia
      POSTGRES_PASSWORD: caramelpsql2
      POSTGRES_DB: recommandationsdb
    ports:
      - "5434:5432"
    expose:
      - '5434'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
    driver: local
